// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Run struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	DockerImage  string         `json:"dockerImage"`
	Mounts       string         `json:"mounts"`
	Parameters   string         `json:"parameters"`
	Data         string         `json:"data"`
	CreatedAt    time.Time      `json:"createdAt"`
	StartedAt    sql.NullTime   `json:"startedAt"`
	FinishedAt   sql.NullTime   `json:"finishedAt"`
	Status       string         `json:"status"`
	HasErrored   bool           `json:"hasErrored"`
	ErrorMessage sql.NullString `json:"errorMessage"`
}
